config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' ,to:'welcome#root' ,as: :root

  resources:posts

  resources:users ,only: [:new, :create]

  resource:session,only: [:new, :create, :destroy]
end

app/models/ability.rb
class Ability < ApplicationRecord
    include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.is_admin?
        can :manage, :all
      end
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :destroy, to: :crud

    can(:crud, Post) do |post|
      post.user == user # true / false
    end

    can(:crud, User) do |user|
      post.user == user # true / false
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to:post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many(:comments, dependent: :destroy)
    validates(:title, presence: true, uniqueness: true)

    validates(
        :body,
        presence: { message: "must exist" },
        length: { minimum: 10 })
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX

    def full_name 
        "#{first_name} #{last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        if session[:user_id].present?
            @current_user ||= User.find session[:user_id] # ||= will only assign
            # @current_user if it is nil. otherwise continue using it as it is
        end
    end
    helper_method :current_user 

    def user_signed_in? 
        current_user.present?
    end

    helper_method :user_signed_in?

    def authenticate_user! 
        unless user_signed_in? 
            flash[:danger] = "You need to be signed in first!"
            redirect_to new_session_path
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create 
        # POST PATH = /questions/:question_id/answers
        @post = Post.find params[:post_id]
        # @question = { id: 1, title: 'your question title', body: 'your question body', ...}
        @comment = Comment.new comment_params 
        # @answer = { body: 'your answer' }
        @comment.post = @post # @answer = { body: 'your answer', question_id: 1 }
        @comment.user = current_user
        if @comment.save
            # AnswerMailer.new_answer(@answer).deliver_now
            redirect_to post_path(@post)
        else 
            # For the list of answers
            @comment = @post.comment.order(created_at: :desc)
            render 'post/show'
        end
    end

    def destroy
        # DELETE PATH = /questions/:question_id/answers/:id
        @comment = Comment.find params[:id]
        if can?(:crud, @comment) 
            @comment.destroy 
            redirect_to post_path(@comment.post)
        else
            # head will send an empty HTTP response with
            # a particular response code, in this case
            # unauthorized 401
            # http://billpatrianakos.me/blog/2013/10/13/list-of-rails-status-code-symbols/
            head :unauthorized
            # redirect_to root_path, alert: 'Not Authorized'
        end
    end

    private

    def comment_params 
        params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize!, only: [:edit, :update, :destroy]
    
    def index

        @posts=Post.all

    end

    def new

        @post=Post.new

    end

    def create
        @post=Post.new post_params
        if @post.save
            flash[:notice] = 'Post created successfully'
           
            redirect_to post_path(@post)
        else
            render :new
        end

    end

    def show

    end

    def edit

    end

    def update
        if @post.update post_params
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
       
        @post.destroy 
        redirect_to posts_path

    end
    
    private
    def post_params
        params.require(:post).permit(:title, :body)

    end

    private
    def find_post

       @post=Post.find params[:id]
    end
    def authorize! 
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @question)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by_email params[:email]
      if user&.authenticate params[:password]
        
        session[:user_id] = user.id 
        redirect_to root_path, notice: "Sign in!"
      else
        flash[:alert] = "Wrong email or password"
        render :new 
      end
    end
  
    def destroy
      session[:user_id] = nil 
      redirect_to root_path, notice: 'Logged Out!'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end

    def create 
        @user = User.new user_params
        if @user.save 
            
            flash[:notice] = "Thank you for signing up!"
            redirect_to root_path
        else 
            flash[:warning] = "Unable to create user"
            render :new 
        end
    end

    def edit
        @user=User.find params[:id]
    end
    def update
       
    end

    private 

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def root 
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <% flash.each do |type, message| %>
        <div class="bg-<%= type %> p-3 rounded mb-2 shadow-sm">
          <%= message %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.present? %>
    <p>
        <%= @post.errors.full_messages.join(', ') %>
    </p>
<% end %>

<%= form_with  model: @post, local: true do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', cols: 50, rows: 5 %>
    </div>
  
    <%= f.submit %>
<% end %>

app/views/posts/_list.html.erb
<div class="row">
    <div class="=col-2">
    </div>

    <div class="col-10">
    <% @posts.each do |post| %>
        <div>
            <h3><%= link_to post.title, posts_path('post') %></h3>
           
        </div>
    <% end %>
    </div>

app/views/posts/edit.html.erb
<h1>Post Edit Page</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<h1>The List of Posts</h1>
<div>
    <% @posts.each do |post| %>
        <%= link_to post do %>
            <li>
                <%= post.title %>
            </li>
        <% end %>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="shadow-sm p-3 mb-5 bg-white rounded overflow-wrap">
    <h1>
        <span class="badge badge-pill badge-info">
            <%= @post.title %>
        </span>
    </h1>
    <p class="shadow-none p-3 mb-5 bg-light rounded"><%= @post.body %></p>

    <% if can? :crud, @post %>
        <div>
            <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-info' %>
            <%= link_to "Delete", post_path(@post), 
                method: :delete, 
                class: 'btn btn-danger',
                data: { confirm: "Are you sure?" } 
            %>
        </div>
    <% end %>
</div>

<hr/>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
<a class="navbar-brand" href="#">Blog On Rails</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
<ul class="navbar-nav mr-auto">

</ul>
<ul class="navbar-nav navigation-links">
    <li class="nav-item nav-links">
        <%= link_to 'Home', root_path %>
    </li>
    
      <% if user_signed_in? %>
          <li class="nav-item nav-links">
              <%= link_to 'New Post', new_post_path %>
          </li>
          <li class="nav-item nav-links">
              <%= link_to 'All Posts', posts_path %>
          </li>
        
          <li class="nav-item nav-links">
              <a><%= current_user.full_name %></a>
          </li>
          <li class="nav-item nav-links">
              <%= link_to "Log Out", session_path, method: :delete, class: 'btn btn-danger' %>
          </li>
      <% else %>
          <li class="nav-item nav-links">
            <%= link_to "Sign In", new_session_path %>
          </li>
          <li class="nav-item nav-links">
          <%= link_to "Sign Up", new_user_path %>
        </li>
      <% end %>
</ul>
</div>
</nav>
<div class="container">

app/views/users/edit.html.erb
<% if @post.errors.present? %>
    <p>
        <%= @post.errors.full_messages.join(', ') %>
    </p>
<% end %>

<%= form_with model: @user, local: true do |f| %>
    <div>
        <%= f.label :fullname %>
        <%= f.text_field :fullname %>
      
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

        <%= f.submit %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>User New Page</h1>
<% if @user.errors.present? %>
    <p>
        <%= @user.errors.full_messages.join(', ') %>
    </p>
<% end %>

<div class="shadow-sm p-3 mb-5 bg-white rounded">
    <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit 'Create User', class: 'btn btn-primary' %>
    <% end %>

app/views/welcome/root.html.erb
  
<h1> Welcome to blog </h1>